[package]
name = "woolyrust"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.69.4"
cmake = "0.1.50"

[dependencies]
anyhow = "1.0.86"

[features]
cuda = []
# metal is automatically assumed on macos buildss